package defpackage;

/* renamed from: fkm  reason: default package */
/* loaded from: classes.dex */
public interface fkm {
    public static final u A;
    public static final u C;
    public static final u H;
    public static final u I;
    public static final u J;
    public static final u K;
    public static final u L;
    public static final u N;
    public static final u O;
    public static final u P;
    public static final u Q;
    public static final u R;
    public static final u S;
    public static final u T;
    public static final u U;
    public static final u V;
    public static final u W;
    public static final u X;
    public static final u Y;
    public static final u Z;
    public static final u c;
    public static final u d;
    public static final u e;
    public static final u g;
    public static final u h;
    public static final u i;
    public static final u j;
    public static final u m;
    public static final u n;
    public static final u o;
    public static final u s;
    public static final u t;
    public static final u u;
    public static final u v;
    public static final u x;
    public static final u y;
    public static final u z;

    static {
        u uVar = new u("2.16.840.1.101.3.4");
        u uVar2 = new u(uVar, "2");
        R = new u(uVar2, "1");
        v = new u(uVar2, "2");
        c = new u(uVar2, "3");
        e = new u(uVar2, "4");
        X = new u(uVar2, "5");
        O = new u(uVar2, "6");
        L = new u(uVar2, "7");
        Z = new u(uVar2, "8");
        m = new u(uVar2, "9");
        x = new u(uVar2, "10");
        H = new u(uVar2, "11");
        U = new u(uVar2, "12");
        new u(uVar2, "13");
        new u(uVar2, "14");
        new u(uVar2, "15");
        new u(uVar2, "16");
        C = new u(uVar2, "17");
        N = new u(uVar2, "18");
        new u(uVar2, "19");
        new u(uVar2, "20");
        u uVar3 = new u(uVar, "1");
        P = uVar3;
        j = jQ.X(uVar3, "1", uVar3, "2");
        new u(uVar3, "3");
        new u(uVar3, "4");
        g = new u(uVar3, "5");
        new u(uVar3, "6");
        new u(uVar3, "7");
        new u(uVar3, "8");
        new u(uVar3, "9");
        y = jQ.X(uVar3, "21", uVar3, "22");
        new u(uVar3, "23");
        new u(uVar3, "24");
        t = new u(uVar3, "25");
        new u(uVar3, "26");
        new u(uVar3, "27");
        new u(uVar3, "28");
        new u(uVar3, "29");
        i = jQ.X(uVar3, "41", uVar3, "42");
        new u(uVar3, "43");
        new u(uVar3, "44");
        V = new u(uVar3, "45");
        new u(uVar3, "46");
        new u(uVar3, "47");
        new u(uVar3, "48");
        new u(uVar3, "49");
        u uVar4 = new u(uVar, "3");
        o = new u(uVar4, "1");
        K = new u(uVar4, "2");
        J = new u(uVar4, "3");
        Y = new u(uVar4, "4");
        h = new u(uVar4, "5");
        I = new u(uVar4, "6");
        u = new u(uVar4, "7");
        z = new u(uVar4, "8");
        n = new u(uVar4, "9");
        Q = new u(uVar4, "10");
        A = new u(uVar4, "11");
        S = new u(uVar4, "12");
        d = new u(uVar4, "13");
        W = new u(uVar4, "14");
        s = new u(uVar4, "15");
        T = new u(uVar4, "16");
    }
}
