package defpackage;

/* renamed from: T5  reason: default package */
/* loaded from: classes.dex */
public interface T5 {
    public static final u A;
    public static final u C;
    public static final u H;
    public static final u I;
    public static final u J;
    public static final u K;
    public static final u L;
    public static final u N;
    public static final u O;
    public static final u P;
    public static final u R;
    public static final u U;
    public static final u V;
    public static final u X;
    public static final u Y;
    public static final u Z;
    public static final u c;
    public static final u e;
    public static final u g;
    public static final u h;
    public static final u i;
    public static final u j;
    public static final u m;
    public static final u o;
    public static final u t;
    public static final u u;
    public static final u v;
    public static final u x;
    public static final u y;
    public static final u z;
    public static final u n = new u("1.3.9999.3.1");
    public static final u Q = new u("1.3.9999.3.4");
    public static final u S = new u("1.3.6.1.4.1.2.267.7.4.4");
    public static final u d = new u("1.3.6.1.4.1.2.267.7.6.5");
    public static final u W = new u("1.3.6.1.4.1.2.267.7.8.7");
    public static final u s = new u("1.3.6.1.4.1.2.267.11.4.4");
    public static final u T = new u("1.3.6.1.4.1.2.267.11.6.5");
    public static final u r = new u("1.3.6.1.4.1.2.267.11.8.7");

    static {
        u uVar = new u("1.3.6.1.4.1.22554");
        u uVar2 = new u(uVar, "1");
        u uVar3 = new u(uVar2, "1");
        u uVar4 = new u(uVar2, "2.1");
        new u(uVar2, "2.2");
        new u(uVar2, "2.3");
        new u(uVar2, "2.4");
        new u(uVar3, "1");
        u uVar5 = new u(uVar3, "2");
        u X2 = jQ.X(uVar4, "1", uVar4, "2");
        new u(uVar5, "1.2");
        new u(uVar5, "1.22");
        new u(uVar5, "1.42");
        new u(X2, "1.2");
        new u(X2, "1.22");
        new u(X2, "1.42");
        u uVar6 = new u(uVar, "2");
        u uVar7 = new u(uVar6, "1");
        R = jQ.X(uVar7, "1", uVar7, "2");
        v = new u(uVar7, "3");
        u uVar8 = new u(uVar6, "2");
        c = new u(uVar8, "1");
        e = new u(uVar8, "2");
        X = new u(uVar8, "3");
        O = new u(uVar8, "4");
        L = new u(uVar8, "5");
        Z = new u(uVar8, "6");
        m = new u(uVar8, "7");
        x = new u(uVar8, "8");
        u uVar9 = new u(uVar6, "3");
        H = new u(uVar9, "1");
        U = new u(uVar9, "2");
        C = new u(uVar9, "3");
        N = new u(uVar9, "4");
        P = new u(uVar9, "5");
        j = new u(uVar9, "6");
        g = new u(uVar9, "7");
        y = new u(uVar9, "8");
        u uVar10 = new u(uVar6, "4");
        new u(uVar10, "1");
        new u(uVar10, "2");
        new u(uVar10, "3");
        new u(uVar10, "4");
        t = jQ.X(uVar10, "5", uVar10, "11");
        i = new u(uVar10, "12");
        u uVar11 = new u(uVar6, "5");
        V = uVar11;
        o = new u(uVar11, "1");
        K = new u(uVar11, "2");
        J = new u(uVar11, "3");
        u X3 = jQ.X(uVar11, "4", uVar6, "6");
        u uVar12 = new u(X3, "1");
        new u(uVar12, "1");
        new u(uVar12, "2");
        new u(uVar12, "3");
        new u(uVar12, "4");
        new u(uVar12, "5");
        new u(uVar12, "6");
        new u(uVar12, "7");
        new u(uVar12, "8");
        new u(uVar12, "9");
        new u(uVar12, "10");
        new u(uVar12, "11");
        new u(uVar12, "12");
        u uVar13 = new u(X3, "2");
        Y = uVar13;
        h = new u(uVar13, "1");
        I = new u(uVar13, "2");
        u = new u(uVar13, "3");
        z = new u(uVar6, "7");
        A = new u(uVar6, "8");
        u X4 = jQ.X(new u(uVar, "3"), "1", uVar, "4");
        new u(X4, "1");
        new u(X4, "2");
        u uVar14 = new u(uVar, "5");
        u uVar15 = new u(uVar14, "1");
        new u(uVar15, "1");
        new u(uVar15, "2");
        new u(uVar15, "3");
        new u(uVar15, "4");
        new u(uVar15, "5");
        new u(uVar15, "6");
        new u(uVar15, "7");
        new u(uVar15, "8");
        new u(uVar15, "9");
        new u(uVar15, "10");
        u uVar16 = new u(uVar14, "2");
        new u(uVar16, "1");
        new u(uVar16, "2");
        new u(uVar16, "3");
        new u(uVar16, "4");
        new u(uVar16, "5");
        new u(uVar16, "6");
        u uVar17 = new u(uVar14, "3");
        new u(uVar17, "1");
        new u(uVar17, "2");
        new u(uVar17, "3");
        new u(uVar17, "4");
        new u(uVar17, "5");
        new u(uVar17, "6");
        new u(uVar17, "7");
        new u(uVar17, "8");
        u X5 = jQ.X(uVar17, "9", uVar14, "4");
        new u(X5, "1");
        new u(X5, "2");
        new u(X5, "3");
        new u(X5, "4");
        new u(X5, "5");
        new u(X5, "6");
        new u(X5, "7");
        new u(X5, "8");
        u uVar18 = new u(uVar14, "5");
        new u(uVar18, "1");
        new u(uVar18, "2");
        new u(uVar18, "3");
        new u(uVar18, "4");
        u uVar19 = new u(uVar14, "6");
        new u(uVar19, "1");
        new u(uVar19, "2");
        new u(uVar19, "3");
        new u(uVar19, "4");
        new u(uVar19, "5");
        new u(uVar19, "6");
        u uVar20 = new u(uVar14, "7");
        u uVar21 = new u(uVar20, "1");
        new u(uVar21, "1");
        new u(uVar21, "2");
        new u(uVar21, "3");
        new u(uVar21, "4");
        new u(uVar21, "5");
        new u(uVar21, "6");
        u uVar22 = new u(uVar20, "2");
        new u(uVar22, "1");
        new u(uVar22, "2");
        new u(uVar22, "3");
        new u(uVar22, "4");
        new u(uVar22, "5");
        new u(uVar22, "6");
        u uVar23 = new u(uVar14, "8");
        new u(uVar23, "1");
        new u(uVar23, "2");
        u X6 = jQ.X(uVar23, "3", uVar14, "9");
        new u(X6, "1");
        new u(X6, "2");
        new u(X6, "3");
    }
}
