package dev.kdrag0n.virtcontainer.ui.terminal;

import android.os.Bundle;
import android.view.View;
import com.termux.terminal.Y;
import java.util.Iterator;

/* loaded from: classes.dex */
public final class TerminalFragment extends c7r {
    public static final /* synthetic */ int x = 0;
    public final pr9 R;

    public TerminalFragment() {
        cwX J = pdD.J(new _d(new csm(22, this), 18));
        this.R = new pr9(g8d.R(TerminalViewModel.class), new UG(J, 11), new UJ(this, J, 11), new bE(J, 11));
    }

    @Override // defpackage.pm2
    public final void W(View view, Bundle bundle) {
        Object obj;
        Bundle bundle2 = ((pm2) this).c;
        String string = bundle2 != null ? bundle2.getString("container_id") : null;
        Bundle bundle3 = ((pm2) this).c;
        String string2 = bundle3 != null ? bundle3.getString("term_session_id") : null;
        Bundle bundle4 = ((pm2) this).c;
        boolean z = bundle4 != null ? bundle4.getBoolean("force_new") : false;
        Bundle bundle5 = ((pm2) this).c;
        String[] stringArray = bundle5 != null ? bundle5.getStringArray("initial_command") : null;
        a().e.H(k().getResources().getConfiguration().isNightModeActive() ? "\n# \n# \"Untitled\" theme for Termux (v2) generated by Hueflake.\n# Copyright (c) 2022 Hueflake. All rights reserved.\n# \n# This generated theme is licensed to undefined for personal use only.\n# Unauthorized use or distribution is strictly prohibited. Modification is allowed for personal use only. All modifications are licensed under the same terms and may not be redistributed.\n# By downloading and using this generated theme, you agree to the license terms.\n# \n# This is a non-transferable and non-exclusive license. You may not redistribute, resell, or sublicense the generated theme. The license agreement will terminate immediately if you do so.\n# You are not assigned any ownership of the content or intellectual property and may only use the content in accordance with these terms.\n# \n# $ AiZee7vu Oebio8za b72dc1307e8f2b6cc3ab9af863118498b0e4bce2 b5e5a8703b76-49cd-817c-32f5d63ca949 $\n# \n\nbackground=#1a1d22\nforeground=#d1d5df\ncursor=#d6e2ff\n# MOD: not for upstream termux\nselection=#3b465c\n\ncolor0=#1a1d22\ncolor1=#ffb0bb\ncolor2=#89e097\ncolor3=#cfd058\ncolor4=#b2c8ff\ncolor5=#d9b9ff\ncolor6=#4ce3d9\ncolor7=#d1d5df\ncolor8=#5e6169\ncolor9=#ffd6db\ncolor10=#b7f4be\ncolor11=#e7e892\ncolor12=#d6e2ff\ncolor13=#ebdaff\ncolor14=#9cf5ed\ncolor15=#eaeef9\ncolor16=#89e097\ncolor17=#ffb3a3\ncolor18=#36393f\ncolor19=#51545b\ncolor20=#acafb8\ncolor21=#eaeef9\ncolor22=#11652d\ncolor52=#873545\ncolor231=#ffffff\ncolor232=#0c0e12\ncolor233=#17191f\ncolor234=#22252a\ncolor235=#2d3036\ncolor236=#383b41\ncolor237=#43454c\ncolor238=#4d5057\ncolor239=#585a62\ncolor240=#62656c\ncolor241=#6c6f77\ncolor242=#767981\ncolor243=#80848c\ncolor244=#8b8e96\ncolor245=#9598a0\ncolor246=#9fa2ab\ncolor247=#a8acb5\ncolor248=#b2b6bf\ncolor249=#bcc0c9\ncolor250=#c6cad3\ncolor251=#d0d4dd\ncolor252=#dadde7\ncolor253=#e3e7f1\ncolor254=#edf1fb\ncolor255=#f9fbff\n    " : "\n# \n# \"Untitled\" theme for Termux (v2) generated by Hueflake.\n# Copyright (c) 2022 Hueflake. All rights reserved.\n# \n# This generated theme is licensed to undefined for personal use only.\n# Unauthorized use or distribution is strictly prohibited. Modification is allowed for personal use only. All modifications are licensed under the same terms and may not be redistributed.\n# By downloading and using this generated theme, you agree to the license terms.\n# \n# This is a non-transferable and non-exclusive license. You may not redistribute, resell, or sublicense the generated theme. The license agreement will terminate immediately if you do so.\n# You are not assigned any ownership of the content or intellectual property and may only use the content in accordance with these terms.\n# \n# $ AiZee7vu Oebio8za b72dc1307e8f2b6cc3ab9af863118498b0e4bce2 b5e5a8703b76-49cd-817c-32f5d63ca949 $\n# \n\nbackground=#f7faff\nforeground=#414653\ncursor=#1448a1\n# MOD: not for upstream termux\nselection=#c9d9f7\n\ncolor0=#f7faff\ncolor1=#af3752\ncolor2=#007e36\ncolor3=#6d6d00\ncolor4=#1e61d6\ncolor5=#8045bf\ncolor6=#007872\ncolor7=#414653\ncolor8=#b1b7c8\ncolor9=#83273c\ncolor10=#005d26\ncolor11=#515100\ncolor12=#1448a1\ncolor13=#5f3290\ncolor14=#005955\ncolor15=#222733\ncolor16=#007e36\ncolor17=#b03c26\ncolor18=#dde4f5\ncolor19=#c8cedf\ncolor20=#696f7d\ncolor21=#222733\ncolor22=#91e59e\ncolor52=#ffb8c2\ncolor231=#ffffff\ncolor232=#ffffff\ncolor233=#fbfcff\ncolor234=#eff4ff\ncolor235=#e4ebfc\ncolor236=#dce3f4\ncolor237=#d3daeb\ncolor238=#cbd1e2\ncolor239=#c2c9d9\ncolor240=#b9c0d0\ncolor241=#b1b7c7\ncolor242=#a8aebe\ncolor243=#9fa5b4\ncolor244=#959bab\ncolor245=#8c92a1\ncolor246=#838898\ncolor247=#797f8e\ncolor248=#6f7583\ncolor249=#656b79\ncolor250=#5b606e\ncolor251=#505663\ncolor252=#454b58\ncolor253=#3a3f4c\ncolor254=#2f3340\ncolor255=#222733\n    ");
        TerminalViewModel a = a();
        if (((Boolean) a.f2798R.e.getValue()).booleanValue() && a.f2800v.getValue() == null) {
            if (string2 != null) {
                ivW ivw = a.f2800v;
                Iterator it = ((Iterable) a.f2799R.f6069R.getValue()).iterator();
                while (true) {
                    if (!it.hasNext()) {
                        obj = null;
                        break;
                    }
                    obj = it.next();
                    if (n3x.v(((ihm) obj).f4698R, string2)) {
                        break;
                    }
                }
                ivw.H((ihm) obj);
            } else {
                l6.z(gvP.o(a), null, 0, new m6J(a, string, z, stringArray, null), 3);
            }
            pby[] pbyArr = kxm.R;
            a.f2791R = new aD8(a.e());
        }
        E(aH9.u(new bkx(22, this), true, -243666159));
        mxC.i(this, new jCF(this, null));
    }

    public final TerminalViewModel a() {
        return (TerminalViewModel) this.R.getValue();
    }

    @Override // defpackage.pm2
    public final void h() {
        for (ihm ihm : (Iterable) a().f2796R.getValue()) {
            Y y = ihm.R;
            B3 b3 = a().R;
            y.f2416R = b3;
            gje gje = y.f2413R;
            if (gje != null) {
                gje.f3897R = b3;
                gje.z();
                gje.f3908m = true;
            }
        }
        this.U = true;
    }
}
