package dev.kdrag0n.virtcontainer.ui.terminal;

import android.content.Context;
import android.graphics.Typeface;
import java.util.List;

/* loaded from: classes.dex */
public final class TerminalViewModel extends kvj {
    public final B3 R;

    /* renamed from: R  reason: collision with other field name */
    public aD8 f2791R;

    /* renamed from: R  reason: collision with other field name */
    public final aME f2792R;

    /* renamed from: R  reason: collision with other field name */
    public final Context f2793R;

    /* renamed from: R  reason: collision with other field name */
    public final doT f2795R;

    /* renamed from: R  reason: collision with other field name */
    public final ivW f2796R;

    /* renamed from: R  reason: collision with other field name */
    public final m5f f2798R;

    /* renamed from: R  reason: collision with other field name */
    public final m_e f2799R;
    public final ivW c;
    public final ivW e;
    public final bLS v;

    /* renamed from: v  reason: collision with other field name */
    public final ivW f2800v;

    /* renamed from: v  reason: collision with other field name */
    public boolean f2801v = true;
    public final ivW X = g4x.O(Typeface.MONOSPACE);

    /* renamed from: R  reason: collision with other field name */
    public final bLS f2794R = pip.R(0, 0, null, 7);

    /* renamed from: R  reason: collision with other field name */
    public final iyL f2797R = new iyL();

    public TerminalViewModel(Context context, aME ame, m_e m_e, doT dot, m5f m5f) {
        this.f2793R = context;
        this.f2792R = ame;
        this.f2799R = m_e;
        this.f2795R = dot;
        this.f2798R = m5f;
        this.f2796R = m_e.f6069R;
        this.R = m_e.R;
        ivW O = g4x.O(null);
        this.f2800v = O;
        ivW O2 = g4x.O(Float.valueOf(((Number) dot.L.v(dot, doT.v[6])).floatValue()));
        this.c = O2;
        ivW O3 = g4x.O("\n# \n# \"Untitled\" theme for Termux (v2) generated by Hueflake.\n# Copyright (c) 2022 Hueflake. All rights reserved.\n# \n# This generated theme is licensed to undefined for personal use only.\n# Unauthorized use or distribution is strictly prohibited. Modification is allowed for personal use only. All modifications are licensed under the same terms and may not be redistributed.\n# By downloading and using this generated theme, you agree to the license terms.\n# \n# This is a non-transferable and non-exclusive license. You may not redistribute, resell, or sublicense the generated theme. The license agreement will terminate immediately if you do so.\n# You are not assigned any ownership of the content or intellectual property and may only use the content in accordance with these terms.\n# \n# $ AiZee7vu Oebio8za b72dc1307e8f2b6cc3ab9af863118498b0e4bce2 b5e5a8703b76-49cd-817c-32f5d63ca949 $\n# \n\nbackground=#1a1d22\nforeground=#d1d5df\ncursor=#d6e2ff\n# MOD: not for upstream termux\nselection=#3b465c\n\ncolor0=#1a1d22\ncolor1=#ffb0bb\ncolor2=#89e097\ncolor3=#cfd058\ncolor4=#b2c8ff\ncolor5=#d9b9ff\ncolor6=#4ce3d9\ncolor7=#d1d5df\ncolor8=#5e6169\ncolor9=#ffd6db\ncolor10=#b7f4be\ncolor11=#e7e892\ncolor12=#d6e2ff\ncolor13=#ebdaff\ncolor14=#9cf5ed\ncolor15=#eaeef9\ncolor16=#89e097\ncolor17=#ffb3a3\ncolor18=#36393f\ncolor19=#51545b\ncolor20=#acafb8\ncolor21=#eaeef9\ncolor22=#11652d\ncolor52=#873545\ncolor231=#ffffff\ncolor232=#0c0e12\ncolor233=#17191f\ncolor234=#22252a\ncolor235=#2d3036\ncolor236=#383b41\ncolor237=#43454c\ncolor238=#4d5057\ncolor239=#585a62\ncolor240=#62656c\ncolor241=#6c6f77\ncolor242=#767981\ncolor243=#80848c\ncolor244=#8b8e96\ncolor245=#9598a0\ncolor246=#9fa2ab\ncolor247=#a8acb5\ncolor248=#b2b6bf\ncolor249=#bcc0c9\ncolor250=#c6cad3\ncolor251=#d0d4dd\ncolor252=#dadde7\ncolor253=#e3e7f1\ncolor254=#edf1fb\ncolor255=#f9fbff\n    ");
        this.e = O3;
        bLS R = pip.R(0, 0, null, 7);
        this.v = R;
        mxC.t(O2, gvP.o(this), new bT6(this, 0));
        mxC.y(O3, gvP.o(this), new bT6(this, 1));
        mxC.y(R, gvP.o(this), new bT6(this, 2));
        l6.z(gvP.o(this), iFn.f4518R, 0, new ciP(this, null), 2);
        mxC.y(l6.E(l6.J(O)), gvP.o(this), new bT6(this, 3));
    }

    public final int e() {
        return ((List) this.f2796R.getValue()).indexOf(this.f2800v.getValue());
    }
}
